name: build-for-gh-pages

on:
    push:
        branches:
            - dev

jobs:
    build-for-gh-pages:
        runs-on: 'ubuntu-latest'

        steps:
            - uses: actions/checkout@v4.1.2
            - uses: actions/setup-node@v4.0.2
              with:
                  node-version-file: '.nvmrc'
            - name: build
              env:
                  REVIEW_VIR_ENCRYPTION_KEY: ${{ secrets.REVIEW_VIR_ENCRYPTION_KEY }}
              run: |
                  npm ci
                  npm run compile
                  npm run build
            - uses: JamesIves/github-pages-deploy-action@v4.5.0
              with:
                  branch: 'gh-pages'
                  folder: dist-pages
